version: "3"
services:
  eurekaservice:
    build: ./EurekaService
  zuulservice:
    build: ./ZuulService
  addressrepositoryservice:
    build: ./AddressRepositoryService
  assessmentrepositoryservice:
    build: ./AssessmentRepositoryService
  batchrepositoryservice:
    build: ./BatchRepositoryService
#  categoryrepositoryservice:
#    build: ./CategoryRepositoryService
  configservice:
    build: ./ConfigService
  graderepositoryservice:
    build: ./GradeRepositoryService
  noterepositoryservice:
    build: ./NoteRepositoryService
  pdfservice:
    build: ./PDFService
  panelfeedbackrepositoryservice:
    build: ./PanelFeedbackRepositoryService
  panelrepositoryservice:
    build: ./PanelRepositoryService
  traineerepositoryservice:
    build: ./TraineeRepositoryService
  trainerrepositoryservice:
    build: ./TrainerRepositoryService
  